import datetime
import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.platypus.flowables import HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_pdf(data, filename="report.pdf"):
    # Ensure directories exist
    os.makedirs(os.path.dirname(os.path.abspath(filename)) or ".", exist_ok=True)
    
    doc = SimpleDocTemplate(filename, pagesize=letter,
                            rightMargin=50, leftMargin=50,
                            topMargin=50, bottomMargin=50)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Center', alignment=1, fontSize=18, fontName='Helvetica-Bold', spaceAfter=10, textColor=colors.HexColor('#2c3e50')))
    styles.add(ParagraphStyle(name='SubCenter', alignment=1, fontSize=12, fontName='Helvetica', spaceAfter=20, textColor=colors.HexColor('#7f8c8d')))
    styles.add(ParagraphStyle(name='Heading', fontSize=14, fontName='Helvetica-Bold', spaceAfter=10, spaceBefore=15, textColor=colors.HexColor('#2980b9')))
    
    Story = []

    # Title
    Story.append(Paragraph("MediCore Hospital", styles['Center']))
    Story.append(Paragraph("Automated Diagnostic & AI Symptom Report", styles['SubCenter']))
    Story.append(HRFlowable(width="100%", color=colors.HexColor('#bdc3c7')))
    Story.append(Spacer(1, 20))

    # Patient details
    Story.append(Paragraph("Patient Information", styles['Heading']))
    patient_info = [
        ["Patient Name:", data.get("name", "Unknown")],
        ["Date of Report:", datetime.datetime.now().strftime("%Y-%m-%d %H:%M")],
        ["Report ID:", f"MC-{abs(hash(data.get('name', '')) + hash(data.get('disease', '')))}"]
    ]
    t = Table(patient_info, colWidths=[120, 300])
    t.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0,0), (0,-1), colors.HexColor('#34495e')),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))
    Story.append(t)
    Story.append(Spacer(1, 20))

    # Symptoms
    Story.append(Paragraph("Reported Symptoms", styles['Heading']))
    Story.append(Paragraph(data.get("symptoms", "N/A"), styles['Normal']))
    Story.append(Spacer(1, 20))

    # AI Prediction
    Story.append(Paragraph("AI Diagnostic Analysis", styles['Heading']))
    
    confidence_val = data.get('confidence', 0)
    if isinstance(confidence_val, (int, float)):
        conf_str = f"{(confidence_val * 100):.1f}%"
    else:
        conf_str = str(confidence_val)

    diag_info = [
        ["Likely Condition:", data.get("disease", "N/A")],
        ["Severity Level:", str(data.get("severity", "N/A")).upper()],
        ["AI Confidence:", conf_str],
        ["Recommended Specialist:", data.get("specialization", "N/A")]
    ]
    
    t2 = Table(diag_info, colWidths=[150, 270])
    t2.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8f9fa')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#e0e0e0')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e0e0e0')),
        ('TOPPADDING', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('TEXTCOLOR', (1,1), (1,1), colors.red if str(data.get("severity")).lower() == "high" else colors.orange if str(data.get("severity")).lower() == "medium" else colors.green),
    ]))
    Story.append(t2)
    Story.append(Spacer(1, 30))

    # Disclaimer
    Story.append(HRFlowable(width="100%", color=colors.HexColor('#bdc3c7')))
    Story.append(Spacer(1, 10))
    Story.append(Paragraph("<b>Disclaimer:</b> This report is generated by an AI algorithm and is intended for informational purposes only. It is not a definitive medical diagnosis. Please consult with the recommended specialist or a registered medical practitioner for clinical evaluation and treatment.", styles['SubCenter']))

    doc.build(Story)
    return filename