import { useEffect, useState } from "react";
import { Download, Printer, FileText } from "lucide-react";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { SeverityBadge } from "@/components/StatusBadges";
import { BrandLogo } from "@/components/BrandLogo";

interface ReportData {
  patient: string;
  symptoms: string;
  result: {
    disease: string;
    severity: "low" | "medium" | "high";
    confidence: number;
    recommended_specialization: string;
  };
  generatedAt: string;
}

const PatientReports = () => {
  const [report, setReport] = useState<ReportData | null>(null);

  useEffect(() => {
    try {
      const raw = sessionStorage.getItem("medicore.lastReport");
      if (raw) setReport(JSON.parse(raw));
    } catch {}
  }, []);

  const onPrint = () => {
    document.documentElement.classList.add("light");
    setTimeout(() => {
      window.print();
      document.documentElement.classList.remove("light");
    }, 50);
  };

  const onDownloadPdf = async () => {
    if (!report) return;
    try {
      const BASE_URL = (import.meta.env.VITE_API_URL as string) || "http://127.0.0.1:8000";
      const res = await fetch(`${BASE_URL}/ai/report`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: report.patient,
          symptoms: report.symptoms
        })
      });
      if (!res.ok) throw new Error("Failed to download PDF");
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "medical_report.pdf";
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error(err);
    }
  };

  if (!report) {
    return (
      <div>
        <PageHeader title="My Reports" subtitle="Generated medical summaries from your AI consultations." />
        <EmptyState
          icon={FileText}
          title="No reports yet"
          description="Run a symptom analysis to generate your first medical summary."
        />
      </div>
    );
  }

  const date = new Date(report.generatedAt);

  return (
    <div>
      <PageHeader
        title="Medical Report"
        subtitle="Auto-generated summary of your most recent AI consultation."
        actions={
          <div className="flex gap-2 no-print">
            <Button variant="outline" onClick={onPrint} className="border-border/60">
              <Printer className="mr-1.5 h-4 w-4" /> Print
            </Button>
            <Button onClick={onDownloadPdf} className="bg-gradient-primary text-primary-foreground">
              <Download className="mr-1.5 h-4 w-4" /> Download PDF
            </Button>
          </div>
        }
      />

      <div className="glass mx-auto max-w-3xl rounded-2xl p-8 print:bg-white print:text-black print:shadow-none">
        <div className="flex items-start justify-between border-b border-border/60 pb-5">
          <BrandLogo />
          <div className="text-right text-xs text-muted-foreground">
            <div>Report ID: MC-{date.getTime().toString(36).toUpperCase()}</div>
            <div>{date.toLocaleString()}</div>
          </div>
        </div>

        <div className="mt-6 grid gap-4 sm:grid-cols-2">
          <Field label="Patient" value={report.patient} />
          <Field label="Recommended Specialization" value={report.result.recommended_specialization} />
          <Field label="Predicted Condition" value={report.result.disease} />
          <Field label="AI Confidence" value={`${(report.result.confidence * 100).toFixed(0)}%`} />
        </div>

        <div className="mt-6">
          <div className="text-[10px] uppercase tracking-widest text-muted-foreground">Severity</div>
          <div className="mt-1.5"><SeverityBadge level={report.result.severity} /></div>
        </div>

        <div className="mt-6">
          <div className="text-[10px] uppercase tracking-widest text-muted-foreground">Reported symptoms</div>
          <p className="mt-1.5 leading-relaxed text-foreground/90">{report.symptoms}</p>
        </div>

        <div className="mt-8 rounded-xl border border-border/60 p-4 text-xs text-muted-foreground">
          This report was generated by MediCore AI for informational purposes only and does not replace
          professional medical advice. Please consult a licensed physician.
        </div>
      </div>
    </div>
  );
};

const Field = ({ label, value }: { label: string; value: string }) => (
  <div>
    <div className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</div>
    <div className="mt-0.5 font-medium">{value}</div>
  </div>
);

export default PatientReports;
